### ISSUE TITLE
Display impl acts differently from `std`'s 

### ISSUE THREAD

**Issue by chipshort** [isaacholt100/bnum#25]
Not sure if this counts as a bug, but since your proclaimed goal is to act like `std`'s integer types:
The `Display` impl does not pad numbers. This test fails:
```rust
#[test]
fn display_pad() {
    use bnum::prelude::*;
    let std = 1u128;
    let bnum: bnum::types::U128 = std.as_();

    assert_eq!(format!("{:05}", std), format!("{:05}", bnum));
}
```

```
panicked at 'assertion failed: `(left == right)`
  left: `"00001"`,
 right: `"1"`'
```

I haven't checked any of the [other formatting options](https://doc.rust-lang.org/std/fmt/index.html), but those might be worth looking at too.

**Comment by isaacholt100** [comment]
I've just published `v0.8.0` which fixes this, so closing this issue.
