### ISSUE TITLE
chore: cleanup TODO.txt from already done things

### ISSUE THREAD

**Issue by dzmitry-lahoda** [isaacholt100/bnum#43]
https://github.com/isaacholt100/bnum/blob/d715a3ebee3ddc983889226fc0e6eac29e25f92b/TODO.txt#L1

**Comment by isaacholt100** [comment]
Hi @dzmitry-lahoda, I can't see any items here which have been completed, which ones were you thinking of? Unless there were other collaborators, I don't think the arbitrary size floats are going to be completed any time soon (and there seems to be less demand for these anyway).
